### ISSUE TITLE
Dynamics

### ISSUE THREAD

**Issue by coryarcangel** [hvandusen/hail-mary#4]
Very low pri (least pri) This should go after after the notes, but before the repeats. It can be hardwired. 

✈
✈
🏎
🏎
🏇
🏇
🏇
🏃
🏃
🐢

A three chord score would be this:
✈
🏇
🐢

**Comment by hvandusen** [comment]
@coryarcangel could u send an example with these included?? thx!

**Comment by coryarcangel** [comment]
🔳🤮🛡️🧍🤬🖤🪄🐝🪄🐝
🔥🔥🔥🔥🔥🔥🔥🔥🔥
⚡ A G C# G# D# C ✈ 🔂 x1
⚡ D F# C# D# A# F 🏎 🔂 x1
⚡ E D# C 🏇 🔂 x1
⚡ G C 🏇 🔂 x1
⚡ G A# 🏃 🔂 x1
⚡ F# E 🏃 🔂 x1
⚡ G 🐢 🔂 x4
⚡ A 🐢 🔂 x6
☁️☁️☁️
🔙🔙
💜

**Comment by coryarcangel** [comment]
We might need to pump up the num of random emojii and fires w new algo - can u keep an eye on that?
